create schema customer_insight;
use customer_insight;

select * from customers;
select * from products;
select * from baskets;
select * from country;
select * from orders;

-- 1. What are the names of all the countries in the country table?
select country_name from  country;
-- 2. What is the total number of customers in the customers table?
select count(customer_id) as total_customers 
from customers;
-- 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
select avg(age) as avg_customer_age 
from customers
where can_email = "yes";
-- 4. How many orders were made by customers aged 30 or older?
select count(case when age>30 then order_id else null end ) as total_orders
from customers c 
left join orders o 
on c.customer_id = o.customer_id;
-- 5. What is the total revenue generated by each product category?
select p.category,concat(sum(p.price)," ","$") as total_revenue
from products p
join baskets b on p.product_id = b.product_id
group by p.category;
-- 6. What is the average price of products in the 'food' category?
select concat(round(avg(price),2)," ","$")as avg_price_of_food_category
from products
where category = "food";
-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?
select sales_channel,count(distinct order_id) as total_orders
from orders
group by sales_channel
order by total_orders desc;
-- 8.What is the date of the latest order made by a customer who can receive marketing emails?
select max(date_shop) as latest_order_date  
from customers c 
left join orders o 
on c.customer_id = o.customer_id
where can_email = "yes";
-- 9. What is the name of the country with the highest number of orders?
with highest_order_country as(select country_name , count(order_id) as total_orders ,
rank() over(order by count(order_id) desc) as country_rnk
from country c 
join orders o 
on c.country_id = o.country_id
group by country_name)
select country_name,total_orders 
from highest_order_country
where country_rnk = 1;
-- 10. What is the average age of customers who made orders in the 'vitamins' product category?
select ceil(avg(c.age)) as avgerage_age_of_customer_who_made_order_from_vitamins_category
from customers c 
left join orders o on c.customer_id = o.customer_id
join baskets b on o.order_id = b.order_id
join products p on b.product_id = p.product_id
where p.category = "vitamins"